### Sources:
### db & app:     https://www.galkov.pro/nextcloud_on_docker/
### nginx & cert: https://hixon.ru/programmirovanie-2/delaem-https-sajtik-s-pomoshhyu-nginx-docker-compose-lets-encrypt.html

version: '3'

networks:
  nextcloud_network:

volumes:
  db:
  app:

services:

  db:
    image: postgres
    networks:
      - nextcloud_network
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: qazwsxedc_123

  app:
    depends_on:
      - db
    image: nextcloud
    restart: always
    ports:
      - 8080:80
      - 4443:443
    networks:
      - nextcloud_network
    volumes:
      #- ./app/html:/var/www/html
      #- ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/themes:/var/www/html/themes
      # абсолютые пути
      - /mnt/hdd/ncdata:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: bati4eli.ru
      LETSENCRYPT_HOST: bati4eli.ru
      LETSENCRYPT_EMAIL: mister.happyend@yandex.ru
      NEXTCLOUD_ADMIN_USER: bati4eli
      NEXTCLOUD_ADMIN_PASSWORD: #TODOPASS
      NEXTCLOUD_DATA_DIR: /mnt/hdd/app/users_data #<- хз нафига.. ничего нет там
      NEXTCLOUD_TRUSTED_DOMAINS: bati4eli.ru

